# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TerraformInstall
    displayName: Validate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: Terraform_Install
            inputs:
              terraformVersion: '1.4.6'
          - task: TerraformTaskV4@4
            displayName: terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
              backendServiceArm: 'AzureIntegration'
              backendAzureRmResourceGroupName: 'rgazdevsea01'
              backendAzureRmStorageAccountName: 'saazdevsea01'
              backendAzureRmContainerName: 'tfstateazdevsea01'
              backendAzureRmKey: 'terraform.tfstate'

