


trigger:
  branches: 
    include:
    - 'feature/*'

variables:
  backendAzureRmResourceGroupName: "rgazdevsea01"
  backendAzureRmStorageAccountName: "saazdevsea01"
  backendAzureRmContainerName: "tfstateazdevsea01"
  backendAzureRmKey: "terraform.tfstate"
  varFile: './tfVars/dev.tfvars'
  environmentServiceNameAzureRM: 'AzureIntegration'
  backendServiceArm: 'AzureIntegration'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
  anyTfChanges: false

pool:
  vmImage: ubuntu-latest

steps:
  - template: yaml-templates/test-template.yml@Azure_Integration_Templates
    parameters:
      backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
      backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
      backendAzureRmContainerName: '$(backendAzureRmContainerName)'
      backendAzureRmKey: '$(backendAzureRmKey)'
      varFile: '$(varFile)'
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'
      backendServiceArm: '$(backendServiceArm)'
      workingDirectory: '$(workingDirectory)'

